# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voiceactressdata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='voiceactressdata.proto',
  package='vad',
  serialized_pb=_b('\n\x16voiceactressdata.proto\x12\x03vad\"\xe9\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x1d\n\x15most_famous_character\x18\x03 \x01(\t\x12%\n\x08\x63ontacts\x18\x04 \x03(\x0b\x32\x13.vad.Person.Contact\x1aW\n\x07\x43ontact\x12\x0c\n\x04info\x18\x01 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x16.vad.Person.OfficeType:\x07\x43OMPANY\"&\n\nOfficeType\x12\x0b\n\x07PRIVATE\x10\x00\x12\x0b\n\x07\x43OMPANY\x10\x01\"/\n\x10VoiceActressBook\x12\x1b\n\x06people\x18\x01 \x03(\x0b\x32\x0b.vad.Person')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PERSON_OFFICETYPE = _descriptor.EnumDescriptor(
  name='OfficeType',
  full_name='vad.Person.OfficeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPANY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=227,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_PERSON_OFFICETYPE)


_PERSON_CONTACT = _descriptor.Descriptor(
  name='Contact',
  full_name='vad.Person.Contact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='vad.Person.Contact.info', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='vad.Person.Contact.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='vad.Person.Contact.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=225,
)

_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='vad.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='vad.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='vad.Person.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='most_famous_character', full_name='vad.Person.most_famous_character', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contacts', full_name='vad.Person.contacts', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_CONTACT, ],
  enum_types=[
    _PERSON_OFFICETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=265,
)


_VOICEACTRESSBOOK = _descriptor.Descriptor(
  name='VoiceActressBook',
  full_name='vad.VoiceActressBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='vad.VoiceActressBook.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=314,
)

_PERSON_CONTACT.fields_by_name['type'].enum_type = _PERSON_OFFICETYPE
_PERSON_CONTACT.containing_type = _PERSON
_PERSON.fields_by_name['contacts'].message_type = _PERSON_CONTACT
_PERSON_OFFICETYPE.containing_type = _PERSON
_VOICEACTRESSBOOK.fields_by_name['people'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['VoiceActressBook'] = _VOICEACTRESSBOOK

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(

  Contact = _reflection.GeneratedProtocolMessageType('Contact', (_message.Message,), dict(
    DESCRIPTOR = _PERSON_CONTACT,
    __module__ = 'voiceactressdata_pb2'
    # @@protoc_insertion_point(class_scope:vad.Person.Contact)
    ))
  ,
  DESCRIPTOR = _PERSON,
  __module__ = 'voiceactressdata_pb2'
  # @@protoc_insertion_point(class_scope:vad.Person)
  ))
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.Contact)

VoiceActressBook = _reflection.GeneratedProtocolMessageType('VoiceActressBook', (_message.Message,), dict(
  DESCRIPTOR = _VOICEACTRESSBOOK,
  __module__ = 'voiceactressdata_pb2'
  # @@protoc_insertion_point(class_scope:vad.VoiceActressBook)
  ))
_sym_db.RegisterMessage(VoiceActressBook)


# @@protoc_insertion_point(module_scope)
